# This is a basic workflow to help you get started with Actions

name: Trigger Email when PR is created or closed

on:
  pull_request_target:
    types:
      - opened
      - reopened
      - closed

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3

      # Runs a single command using the runners shell
      - name: Send mail
        uses: dawidd6/action-send-mail@v3
        with:
           server_address: smtp.gmail.com
           server_port: 465
           username: ${{secrets.MAIL_USERNAME}}
           password: ${{secrets.MAIL_PASSWORD}}
           subject: PR created / closed for ${{ github.event.repository.name }}
           to: ${{secrets.MAIL_TO}}
           from: ${{secrets.MAIL_FROM}}
           secure: true
           body: Build job of ${{github.repository}} completed successfully!
           html_body: <h3>Build job of ${{github.repository}} completed successfully!</h3>
           #cc: kyloren@example.com,leia@example.com
           #bcc: r2d2@example.com,hansolo@example.com
           #reply_to: luke@example.com
           #in_reply_to: <random-luke@example.com>
           ignore_cert: true
           convert_markdown: true
           #attachments: attachments.zip,git.diff,./dist/static/*.js
           #priority: low
           
      - name: 'Comment on PR'
        uses: actions/github-script@v3
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            var fs = require('fs');
            var issue_number = Number(fs.readFileSync('./NR'));
            await github.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: issue_number,
              body: 'Everything is OK. Thank you for the PR!'
            });     
