# This is a basic workflow to help you get started with Actions

name: Trigger Email when PR is opened, reopened or closed

on:
  pull_request_target:
    types:
      - opened
      - reopened
      - closed
      
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Send mail
        uses: dawidd6/action-send-mail@v3
        with:
           server_address: smtp.gmail.com
           server_port: 465
           username: ${{secrets.MAIL_USERNAME}}
           password: ${{secrets.MAIL_PASSWORD}}
           subject: PR created / closed for ${{ github.event.repository.name }}
           to: ${{secrets.MAIL_TO}}
           from: ${{secrets.MAIL_FROM}}
           secure: true
           body: ${{github.context.payload}}
           html_body: ${{github.context.payload}}
           ignore_cert: true
           convert_markdown: true
           
